// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/jafajardo/GolandProjects/awesomeProject/testmockuniotarios/Calculadora.go

// Package testmockuniotarios is a generated GoMock package.
package testmockuniotarios

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFiguraGeometrica is a mock of FiguraGeometrica interface.
type MockFiguraGeometrica struct {
	ctrl     *gomock.Controller
	recorder *MockFiguraGeometricaMockRecorder
}

// MockFiguraGeometricaMockRecorder is the mock recorder for MockFiguraGeometrica.
type MockFiguraGeometricaMockRecorder struct {
	mock *MockFiguraGeometrica
}

// NewMockFiguraGeometrica creates a new mock instance.
func NewMockFiguraGeometrica(ctrl *gomock.Controller) *MockFiguraGeometrica {
	mock := &MockFiguraGeometrica{ctrl: ctrl}
	mock.recorder = &MockFiguraGeometricaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiguraGeometrica) EXPECT() *MockFiguraGeometricaMockRecorder {
	return m.recorder
}

// CalcularArea mocks base method.
func (m *MockFiguraGeometrica) CalcularArea() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalcularArea")
	ret0, _ := ret[0].(float64)
	return ret0
}

// CalcularArea indicates an expected call of CalcularArea.
func (mr *MockFiguraGeometricaMockRecorder) CalcularArea() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalcularArea", reflect.TypeOf((*MockFiguraGeometrica)(nil).CalcularArea))
}
